name: CI
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'
jobs:

  make-and-test-cookie:
    name: Cookie Instantiation Tests
    runs-on: ubuntu-20.04
    env:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: |
          # setup
          python3 -m pip install -r requirements.txt
          git config --global user.name 'actions'
          git config --global user.email 'actions-user@users.noreply.github.com'

          # make cookie
          mkdir -p ../cut-cookie/
          cookiecutter . --no-input -o ../cut-cookie/
          cd ../cut-cookie/cut-dishtiny-project

          # deploy cookie
          git remote set-url origin "https://${PERSONAL_ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git checkout -b cut-cookie
          git push origin cut-cookie --force
